class CSException(Exception):
    pass


class CSError(CSException):
    pass
